### PR TITLE
Fix the build system, modernize C++, optionally unbundle libs, provide pkg-config

### PR DESCRIPTION
**Pull request by SoapZA**
Dear @pezmaster31 
I would like to use bamtools, but had to make some changes to make it amenable for more general use and for distros in particular. The changes:

1. Use **GNUInstallDirs** in order to be able to change all install locations. This makes it much easier for multilib-aware distributions to change the lib dir. This also solves https://github.com/pezmaster31/bamtools/pull/82, but in a much better and more generalisable way.
2. Do not use `-fPIC` globally! While I understand that this works around an ancient CentOS bug, enabling `-fPIC` for static libraries on x86 causes undue register pressure, due to the need for keeping the Global Offset Table (GOT) address in a register. Instead, CMake knows that only for shared objects, `-fPIC` has to be added, but not for static libraries. See https://nebelwelt.net/publications/files/12TRpie.pdf for the toll position independent code takes on x86. Again, if for security reasons of address space layout randomization (ASLR), users can always add `-fPIC -fPIE` to `CXXFLAGS` is they so desire.
3. I fixed the previous C++11 issues caused by instantiating `std::make_unique` with explicit template arguments, a bad practice, as template argument deduction is required for universal/forwarding references to work in C++11.
4. Fix narrowing failures due to writing 255 into a (on most platforms signed) char. The cast is still somewhat ugly, but at least allows it to compile, albeit invoking implementation-defined/compiler-dependent behaviour.
5. Do not hardcode C++98 into the build system, this makes it hard for modern code to interface with it! Think of all the suppressed implicitly generated move constructors! Now, it builds in C++98, C++11 and C++14 modes.
6. Do not muck around with CMake's `*_FLAGS_*` (such as `CMAKE_CXX_FLAGS_RELEASE`) variables. Changing these is problematic, as Gentoo for instance changes the `CMAKE_BUILD_TYPE` to do QA checks of its own. Leave the default flags as they are, and let the user be in full control of setting them up.
7. I fixed some minor parts, where the build system was not truly out-of-source. This should also fix https://github.com/pezmaster31/bamtools/pull/117
8. Update the bundled JsonCpp to the latest version
9. First try to use the system JsonCpp, and as a fallback the bundled one. This is important for distros, as bundled libraries are a security nightmare.
10. Install `.pc` files along with the library. This makes it **so** much easier to discover from within the build systems of reverse dependencies.

I'm sure @sjackman, @wookietreiber, @mr-c would appreciate these fixes too 😉

### CODE REVIEW

**Comment by sjackman** [comment]
:+1: for `optionally unbundle libs`. Thanks, David!

**Comment by wookietreiber** [comment]
👍

**Comment by armintoepfer** [comment]
LGTM

**Comment by SoapZA** [comment]
All commits have been merged as separate PRs, most of Bamtools should be buildable with a modern toolchain and modern CMake semantics now.

**Pull request closed without merging**
