### PR TITLE
Support CIGARs with >65535 operators

### PR DESCRIPTION
**Pull request by lh3**
This PR implements the agreed solution to long cigar (samtools/hts-specs#40). I have tested the reader and the `BamWriterPrivate::WriteCoreAlignment()` method. However, I am not sure how to test the other writer `BamWriterPrivate::WriteAlignment()`. Some help is needed to confirm this PR really works. Thanks.

### CODE REVIEW

**Comment by pezmaster31** [comment]
Oh, great! Thanks, Heng. Yeah, I'll check this out sometime here soon.

**Comment by lh3** [comment]
Thanks! Forgot to say: you can find sample data [here](http://lh3lh3.users.sourceforge.net/data/cigar-64k/), file `cigar-64k.sam.gz` and `cigar-64k.bam`. The precompiled samtools executable there already works with long cigar. You may use that to check the results, too.

**Comment by SoapZA** [comment]
Please run ./tools/format-all and rebase out the merge commits.

**Comment by lh3** [comment]
This PR was created before 2.4.2. The formatting of bamtools has been substantially changed with clang-format, which makes rebase very difficult. I will create a new PR with all the changes in one batch. I am closing this PR for now. A new one is coming later today.

**Comment by lh3** [comment]
See #170 for an update to this PR. Thank you!

**Pull request closed without merging**
