### PR TITLE
Fix for issue #85

### PR DESCRIPTION
**Pull request by marc-sturm**
Hi, I created a patch to get rid of the MinGW warnings.

### CODE REVIEW

**Comment by mr-c** [comment]
@marc-sturm Wouldn't it be better to just undefine `API_EXPORT` if MinGW is detected?

**Comment by marc-sturm** [comment]
"API_EXPORT" makes no sense in conjunction with "inline", so I fixed those lines only.
I guess for all other places where it occurs, it is needed to export the functions to the library...

**Comment by mr-c** [comment]
Right. Wish there was a CI set up on this repo to test your proposed changes.

@pezmaster31 I recommend opening up co-maintainership to deal with the issue & PR backlog unless you recommend https://github.com/PacificBiosciences/pbbam over this library

**Comment by SoapZA** [comment]
@marc-sturm could you rebase these changes?

**Pull request closed without merging**
